//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantan.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kantan.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery-dl.exe.
        /// </summary>
        internal static string EXE_GALLERYDL {
            get {
                return ResourceManager.GetString("EXE_GALLERYDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magic.mgc.
        /// </summary>
        internal static string F_MAGIC {
            get {
                return ResourceManager.GetString("F_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ifconfig.co/.
        /// </summary>
        internal static string IFConfigUrl {
            get {
                return ResourceManager.GetString("IFConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.deviantart.com=images-wixmp.
        /// </summary>
        internal static string KV_Media {
            get {
                return ResourceManager.GetString("KV_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .svg.
        /// </summary>
        internal static string KV_Media_EW {
            get {
                return ResourceManager.GetString("KV_Media_EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pbs.twimg.com/profile_banners/.
        /// </summary>
        internal static string KV_Media_SW {
            get {
                return ResourceManager.GetString("KV_Media_SW", resourceCulture);
            }
        }
    }
}
